global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cu-dashy'
    static_configs:
      - targets: ['app:80']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Configuration pour le monitoring de Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Règles d'alerte
rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'  # À décommenter si on ajoute AlertManager

# Configuration des règles de stockage
storage:
  tsdb:
    retention_time: 15d
    retention_size: 5GB
